version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "7777:7777"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JOLOKIA_PORT: 7777
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  influxdb_v2:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    ports:
      - "9999:9999"
  telegraf:
    image: telegraf:latest
    restart: always
    environment:
      INFLUX_HOST: http://influxdb_v2:9999/
      INFLUX_TOKEN: my-token
      INFLUX_ORG: my-org
      INFLUX_BUCKET: my-bucket
      JOLOKIA_AGENT_URL: http://kafka:7777/jolokia
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    depends_on:
      - influxdb_v2
    volumes:
      - $PWD/kafka-zk-jolokia.conf:/etc/telegraf/telegraf.conf:ro
  dependencies-all:
    image: ubuntu:18.04
    command: sleep infinity
    depends_on:
      - zookeeper
      - kafka
      - influxdb_v2
